import Foundation
import Testing

@testable import Trio

/// Deterministic PRNG so noise tests are reproducible.
private struct XorshiftRNG {
    var state: UInt64
    mutating func next() -> UInt64 {
        state ^= state << 13
        state ^= state >> 7
        state ^= state << 17
        return state
    }

    mutating func below(_ bound: Int) -> Int {
        Int(next() % UInt64(bound))
    }
}

@Suite("Reed-Solomon Tests") struct ReedSolomonTests {
    // Golden vectors generated by the validated Python prototype
    // (scratch: tdm_prototype.py) — they pin the GF(256) arithmetic,
    // generator polynomial and byte order across implementations.
    private let goldenMessage: [UInt8] = Array("Trio dense matrix golden vector".utf8)

    @Test("Parity matches the reference implementation (nsym=16)") func goldenParity16() {
        let codeword = ReedSolomon.encode(goldenMessage, paritySymbols: 16)
        let parity = Array(codeword.suffix(16))
        #expect(parity == [UInt8]([
            0x46, 0x03, 0x2A, 0x55, 0x3D, 0xFB, 0x37, 0x2F,
            0x0B, 0x76, 0xB9, 0x15, 0x2C, 0x06, 0xD7, 0x98
        ]))
    }

    @Test("Parity matches the reference implementation (nsym=32)") func goldenParity32() {
        let codeword = ReedSolomon.encode(goldenMessage, paritySymbols: 32)
        let parity = Array(codeword.suffix(32))
        #expect(parity == [UInt8]([
            0x46, 0x55, 0xA1, 0xC3, 0x31, 0x50, 0xD2, 0xDB,
            0x03, 0x6B, 0x2F, 0x7D, 0x7F, 0x34, 0x0D, 0x3F,
            0xCC, 0xEC, 0x13, 0x66, 0x79, 0xB6, 0x32, 0x5C,
            0xEA, 0x9F, 0x41, 0xFD, 0xEE, 0x33, 0x2D, 0xC7
        ]))
    }

    @Test("A clean codeword decodes to the message") func cleanDecode() {
        let codeword = ReedSolomon.encode(goldenMessage, paritySymbols: 32)
        #expect(ReedSolomon.decode(codeword, paritySymbols: 32) == goldenMessage)
    }

    @Test("Up to nsym/2 byte errors are corrected") func errorCorrection() {
        var rng = XorshiftRNG(state: 42)
        for trial in 0 ..< 50 {
            let messageLength = 1 + rng.below(191)
            let message = (0 ..< messageLength).map { _ in UInt8(rng.below(256)) }
            let nsym = 64
            let codeword = ReedSolomon.encode(message, paritySymbols: nsym)

            var corrupted = codeword
            let errorCount = rng.below(nsym / 2 + 1)
            var positions = Set<Int>()
            while positions.count < min(errorCount, corrupted.count) {
                positions.insert(rng.below(corrupted.count))
            }
            for p in positions {
                corrupted[p] ^= UInt8(1 + rng.below(255))
            }

            #expect(
                ReedSolomon.decode(corrupted, paritySymbols: nsym) == message,
                "trial \(trial) with \(positions.count) errors"
            )
        }
    }

    @Test("More than nsym/2 errors do not silently pass as this message") func overloadFails() {
        var rng = XorshiftRNG(state: 7)
        let message = (0 ..< 100).map { _ in UInt8(rng.below(256)) }
        let codeword = ReedSolomon.encode(message, paritySymbols: 32)
        var silentWrong = 0
        for _ in 0 ..< 30 {
            var corrupted = codeword
            var positions = Set<Int>()
            while positions.count < 20 { // 20 > 16 correctable
                positions.insert(rng.below(corrupted.count))
            }
            for p in positions {
                corrupted[p] ^= UInt8(1 + rng.below(255))
            }
            if let decoded = ReedSolomon.decode(corrupted, paritySymbols: 32), decoded == message {
                silentWrong += 1
            }
        }
        // Miscorrection to a *different* codeword is possible (the outer hash
        // catches it); recovering the original from >t errors is not.
        #expect(silentWrong == 0)
    }
}

@Suite("Dense Matrix Code Tests") struct DenseMatrixCodeTests {
    @Test("Scramble mask matches the reference implementation") func goldenScrambleMask() {
        let mask = DenseMatrixCode.scrambleMask(count: 16)
        #expect(mask == [UInt8]([
            0x97, 0xEB, 0x98, 0x49, 0x79, 0x48, 0x2F, 0xFE,
            0x10, 0x50, 0x65, 0xDC, 0x88, 0xB6, 0xD0, 0x35
        ]))
    }

    /// Interior data-region luminances of a rendered symbol: black cell = 0,
    /// white = 255, exactly what a perfect camera would sample.
    private func interiorLuminances(of symbol: DenseMatrixCode.Symbol) -> [Float] {
        let n = symbol.size
        let border = DenseMatrixCode.borderModules
        let inner = n - 2 * border
        var out = [Float]()
        out.reserveCapacity(inner * inner)
        for row in 0 ..< inner {
            for col in 0 ..< inner {
                out.append(symbol.modules[(border + row) * n + (border + col)] ? 0 : 255)
            }
        }
        return out
    }

    private func randomPayload(_ count: Int, seed: UInt64) -> Data {
        var rng = XorshiftRNG(state: seed)
        return Data((0 ..< count).map { _ in UInt8(rng.below(256)) })
    }

    @Test("Symbols pick the smallest sufficient grid") func sizeSelection() {
        #expect(DenseMatrixCode.pickSize(payloadLength: 200) == 121)
        #expect(DenseMatrixCode.pickSize(payloadLength: 3000) != nil)
        #expect(DenseMatrixCode.pickSize(payloadLength: 100_000) == nil)
    }

    @Test("Payload survives a clean encode/decode roundtrip at several sizes") func cleanRoundtrip() throws {
        for (i, count) in [200, 1500, 3000, 6000].enumerated() {
            let payload = randomPayload(count, seed: UInt64(i + 1))
            let symbol = try DenseMatrixCode.encode(payload: payload)
            let decoded = DenseMatrixCode.decode(interiorLuminances: interiorLuminances(of: symbol), size: symbol.size)
            #expect(decoded == payload, "size \(count)")
        }
    }

    @Test("Decode succeeds with 1% of cells flipped") func noisyRoundtrip() throws {
        var rng = XorshiftRNG(state: 99)
        let payload = randomPayload(3000, seed: 5)
        let symbol = try DenseMatrixCode.encode(payload: payload)
        var luminances = interiorLuminances(of: symbol)
        let flips = luminances.count / 100
        var positions = Set<Int>()
        while positions.count < flips {
            positions.insert(rng.below(luminances.count))
        }
        for p in positions {
            luminances[p] = 255 - luminances[p]
        }
        let decoded = DenseMatrixCode.decode(interiorLuminances: luminances, size: symbol.size)
        #expect(decoded == payload)
    }

    @Test("Decode succeeds from any rotation") func rotationRoundtrip() throws {
        let payload = randomPayload(1000, seed: 11)
        let symbol = try DenseMatrixCode.encode(payload: payload)
        let inner = symbol.size - 2 * DenseMatrixCode.borderModules
        var luminances = interiorLuminances(of: symbol)
        for rotation in 0 ..< 4 {
            let decoded = DenseMatrixCode.decode(interiorLuminances: luminances, size: symbol.size)
            #expect(decoded == payload, "rotation \(rotation)")
            // Rotate the luminance grid the way a sideways camera would.
            var rotated = [Float](repeating: 0, count: luminances.count)
            for row in 0 ..< inner {
                for col in 0 ..< inner {
                    rotated[col * inner + (inner - 1 - row)] = luminances[row * inner + col]
                }
            }
            luminances = rotated
        }
    }

    @Test("Grossly corrupted symbols are rejected, not mis-decoded") func corruptionRejected() throws {
        var rng = XorshiftRNG(state: 3)
        let payload = randomPayload(2000, seed: 8)
        let symbol = try DenseMatrixCode.encode(payload: payload)
        var luminances = interiorLuminances(of: symbol)
        var positions = Set<Int>()
        while positions.count < luminances.count / 10 { // 10% noise, far beyond correction
            positions.insert(rng.below(luminances.count))
        }
        for p in positions {
            luminances[p] = 255 - luminances[p]
        }
        let decoded = DenseMatrixCode.decode(interiorLuminances: luminances, size: symbol.size)
        #expect(decoded == nil || decoded == payload)
        #expect(decoded != Data([0]))
    }

    @Test("Flat input (no symbol in view) is rejected cheaply") func flatInput() {
        let n = DenseMatrixCode.sizes[0]
        let inner = n - 2 * DenseMatrixCode.borderModules
        let flat = [Float](repeating: 128, count: inner * inner)
        #expect(DenseMatrixCode.decode(interiorLuminances: flat, size: n) == nil)
    }

    @Test("A device-setup transfer rides the dense matrix end to end") func transferEndToEnd() throws {
        var transfer = DeviceSetupTransfer()
        transfer.createdAt = Date()
        transfer.hostName = "Kid's iPhone"
        var backup = TrioSettingsBackup()
        backup.insulinConcentrationFactor = 1
        backup.basalProfile = [BasalProfileEntry(start: "00:00", minutes: 0, rate: 0.85)]
        transfer.backup = backup
        transfer.remoteControl = RemoteControlTransfer(
            enabled: true,
            sharedSecret: "legacy-secret",
            apnsTeamId: "TEAM",
            apnsKeyId: "KEY",
            apnsKey: String(repeating: "K", count: 200),
            fcmServiceAccountJSON: nil,
            followers: [PairedFollower(
                id: "F00",
                name: "Mom",
                secret: "u8Fyar0N5wCCPzXKvV9V3wJ0lC0T3rH2m8Q1a2b3c4d=",
                createdAt: Date(),
                lastSequence: 41,
                lastSeenAt: nil
            )]
        )

        let payload = try DeviceSetupPayloadCoder.compress(transfer)
        let symbol = try DenseMatrixCode.encode(payload: payload)
        let decodedPayload = try #require(
            DenseMatrixCode.decode(interiorLuminances: interiorLuminances(of: symbol), size: symbol.size)
        )
        let decoded = try DeviceSetupPayloadCoder.decompress(decodedPayload)

        #expect(decoded.hostName == "Kid's iPhone")
        #expect(decoded.remoteControl?.followers?.first?.lastSequence == 41)
        #expect(decoded.remoteControl?.followers?.first?.secret == "u8Fyar0N5wCCPzXKvV9V3wJ0lC0T3rH2m8Q1a2b3c4d=")
        #expect(decoded.backup?.basalProfile?.first?.rate == 0.85)
    }
}
