import Foundation
import Testing

@testable import Trio

/// Reference vectors were generated by running pumpX2's own EC-JPAKE
/// implementation (`io.particle.crypto.EcJpake`, backed by BouncyCastle) with a
/// deterministic random source, and dumping the exact scalars it consumed. The
/// scripted random source below replays those scalars, so a passing test means
/// this Swift port produces byte-identical wire output to the implementation
/// that is known to work against real pumps.
private enum TandemTestVectors {
    // Pairing code "123456", every ephemeral scalar 1, every random block zero.
    static let allZeroPairingCode = "123456"
    static let allZeroScalars = ["01", "01", "01", "01", "01"]
    static let allZeroBlocks = [String(repeating: "00", count: 16), String(repeating: "00", count: 16)]
    static let allZeroClientRound1 =
        "41046b17d1f2e12c4247f8bce6e563a440f277037d812deb33a0f4a13945d898c2964fe342e2fe1a7f9b8ee7eb4a7c0f9e162bce33576b315ececbb6406837bf51f5" +
        "41046b17d1f2e12c4247f8bce6e563a440f277037d812deb33a0f4a13945d898c2964fe342e2fe1a7f9b8ee7eb4a7c0f9e162bce33576b315ececbb6406837bf51f5" +
        "20fc2412bf08cbb28d9f31370b161070299acf2d360c5de76e162821af4508b913" +
        "41046b17d1f2e12c4247f8bce6e563a440f277037d812deb33a0f4a13945d898c2964fe342e2fe1a7f9b8ee7eb4a7c0f9e162bce33576b315ececbb6406837bf51f5" +
        "41046b17d1f2e12c4247f8bce6e563a440f277037d812deb33a0f4a13945d898c2964fe342e2fe1a7f9b8ee7eb4a7c0f9e162bce33576b315ececbb6406837bf51f5" +
        "20fc2412bf08cbb28d9f31370b161070299acf2d360c5de76e162821af4508b913"
    static let allZeroServerRound1 =
        "41046b17d1f2e12c4247f8bce6e563a440f277037d812deb33a0f4a13945d898c2964fe342e2fe1a7f9b8ee7eb4a7c0f9e162bce33576b315ececbb6406837bf51f5" +
        "41046b17d1f2e12c4247f8bce6e563a440f277037d812deb33a0f4a13945d898c2964fe342e2fe1a7f9b8ee7eb4a7c0f9e162bce33576b315ececbb6406837bf51f5" +
        "201a91f0c52756d7950b378afd57db4dc9690d61059d20c9ca98621fdabaf0f544" +
        "41046b17d1f2e12c4247f8bce6e563a440f277037d812deb33a0f4a13945d898c2964fe342e2fe1a7f9b8ee7eb4a7c0f9e162bce33576b315ececbb6406837bf51f5" +
        "41046b17d1f2e12c4247f8bce6e563a440f277037d812deb33a0f4a13945d898c2964fe342e2fe1a7f9b8ee7eb4a7c0f9e162bce33576b315ececbb6406837bf51f5" +
        "201a91f0c52756d7950b378afd57db4dc9690d61059d20c9ca98621fdabaf0f544"
    static let allZeroClientRound2 =
        "410440f365e04fb72099d5c0e82007b69537f80bbe379e2a586038ce1978850eb887c93e7a858ef6099488627483d3b64eabae3bafc035ecef6130bc8cf624e80241" +
        "41045ecbe4d1a6330a44c8f7ef951d4bf165e6c6b721efada985fb41661bc6e7fd6c8734640c4998ff7e374b06ce1a64a2ecd82ab036384fb83d9a79b127a27d50322" +
        "00e199f795e5d8a45978d44e3f8097ed4eae65a84124c6484e713a2c4bcbf65aa"
    static let allZeroServerRound2 =
        "030017" +
        "410440f365e04fb72099d5c0e82007b69537f80bbe379e2a586038ce1978850eb887c93e7a858ef6099488627483d3b64eabae3bafc035ecef6130bc8cf624e80241" +
        "41045ecbe4d1a6330a44c8f7ef951d4bf165e6c6b721efada985fb41661bc6e7fd6c8734640c4998ff7e374b06ce1a64a2ecd82ab036384fb83d9a79b127a27d50322" +
        "030cf8dbc61469da2fb30a417016706055e454ec323c2e1ff9aa3afbde6f07dee"
    static let allZeroDerivedSecret = "c99c68700508650bc1eaae1c8d3b8d38c7cafea8bca97fc967b92a0b947bc078"

    // Pairing code "654321", non-trivial scalars.
    static let counterPairingCode = "654321"
    static let counterClientScalars = [
        "1112131415161718191a1b1c1d1e1f202122232425262728292a2b2c2d2e2f30",
        "3132333435363738393a3b3c3d3e3f404142434445464748494a4b4c4d4e4f50",
        "5152535455565758595a5b5c5d5e5f606162636465666768696a6b6c6d6e6f70",
        "7172737475767778797a7b7c7d7e7f808182838485868788898a8b8c8d8e8f90",
        "a1a2a3a4a5a6a7a8a9aaabacadaeafb0b1b2b3b4b5b6b7b8b9babbbcbdbebfc0"
    ]
    static let counterClientBlocks = [
        "9192939495969798999a9b9c9d9e9fa0",
        "c1c2c3c4c5c6c7c8c9cacbcccdcecfd0"
    ]
    static let counterClientRound1 =
        "41044c6336e3b8b3de771b613a1c7a1734834cd69c1a4f5ffecb240c63bc0ddb1574f6896c5d14ca44e0037791c2300333259a71b901e5258575d107e5b8ac48b424" +
        "41040c7fcc321c77119203dbe79864907e4f0a01917789dea2d4731531a52a22e2bac1766d21e4617d72fbbef87d6edf2d8f80b526956e3c2c1701f16b7f311500c6" +
        "20f1e5539b41471f3d972d97f95b70713ef5928314861e76e75d8d1681bdd79cca" +
        "4104be577b5b33b8c3dcfa81858593d84938203e78ba10f87fb75376eea937d5592af52bdc641c43adea9e342ffc6fdbfe5c863c9f6ed30471999a1d01ecf54065be" +
        "41048ab547c60e31c0032115c895ddeed6d8319b5da62e4a92ded1df03a879b190cdc501aafa10c3d2cf4566c6c53667b9626d12e97ed229ce90b8ca29a06427dd58" +
        "209bda239d550f5d476e798496b01743d301dedbf665bc11716d4c7718ecd836c9"
    static let counterServerRound1 =
        "41048ab547c60e31c0032115c895ddeed6d8319b5da62e4a92ded1df03a879b190cdc501aafa10c3d2cf4566c6c53667b9626d12e97ed229ce90b8ca29a06427dd58" +
        "4104382cd64e093fd13ef7a0ef7df7813cc1b1dc5114456175b83f89848adeeddd84ee69cf25dc149a3430eb452fb9e8216c946a9b67f1142918884e81814d23f25f" +
        "20192532cc688a720d794c0b7c99f6c4ab43190a32146023a17fde3a70932680f9" +
        "4104a79231e57ed598628f02d4a92c680fbd87f19a077af5af6616194af5269381d1e9ee4661df4dc0b391234ddbfb425f0d480676f3e54e197026c826abfa13ed89" +
        "41043c06b1c7fc699ccd77641f46f0c0492cfd76bf784e4ed1968f13ae1d646568cbae90b48f7cf4acfde4fc09b124c424aeba66f604aef18c7201be06272b905899" +
        "20e4630af76fb8b23c68fbd0c8bb433f1d6a081d10a4c4abfe5689aa0a331ff55f"
    static let counterClientRound2 =
        "4104346ff217aa5c55f57ba369b8cc0af5590a4aeb064fe662bec0afff97a5057ec7a6e128d46dba6680d0476cfe36d9558843d0eddf2d29e57d9ea3717f9b51fc32" +
        "41049e1ad7017f9f6e30b4d9f866c83f7a66152f5b430d0c06bce8d036f06997f298b8eb967bccb4fd4f2d00043806b88e3c30a3cae6c59dc5931ffefc1e78d923b5" +
        "20548fb7b40815ed142210066c9daac13ef122f4892918def51e897ef3d949c945"
    static let counterServerRound2 =
        "030017" +
        "41043278012819377a486113d6b064a6209d4f4990048e8f4e28f37a7a8883fa5b55349e76c05d433900e1f96d1f0ba5ef9b00b1177f8f1a79e1d476bf846b249985" +
        "4104a44bed2c2e1d020236391a45b4d680a2d2e3d0e73b4eaabe136a52d4a8c9fae34c70d1eee51c7ee67dca9013ac002ccdfb3385aa3f3a846c774e2fffa597474a" +
        "20aaf357d38fc39f49a7b9fd30f604f8f020699caa59dfc1c3658e0c1160f69725"
    static let counterDerivedSecret = "79c03e685d775345070dd2c251a29e918e0e282c595b018f34d3eb8535f452af"

    // Uncompressed encoding of the P-256 generator.
    static let generatorEncoding =
        "046b17d1f2e12c4247f8bce6e563a440f277037d812deb33a0f4a13945d898c2964fe342e2fe1a7f9b8ee7eb4a7c0f9e162bce33576b315ececbb6406837bf51f5"
}

/// Replays a fixed script of scalars and random blocks, so the handshake is
/// byte-for-byte reproducible.
private final class ScriptedRandomSource: TandemJpakeRandomSource {
    private var scalars: [TandemBigUInt]
    private var blocks: [Data]

    init(scalarHex: [String], blockHex: [String]) {
        scalars = scalarHex.map { TandemBigUInt(hex: $0)! }
        blocks = blockHex.map { Data(hexString: $0)! }
    }

    func randomBytes(count: Int) throws -> Data {
        guard !blocks.isEmpty else { throw TandemJpakeError.randomnessUnavailable }
        let block = blocks.removeFirst()
        guard block.count == count else { throw TandemJpakeError.randomnessUnavailable }
        return block
    }

    func randomScalar(order _: TandemBigUInt) throws -> TandemBigUInt {
        guard !scalars.isEmpty else { throw TandemJpakeError.randomnessUnavailable }
        return scalars.removeFirst()
    }
}

private extension Data {
    init?(hexString: String) {
        guard hexString.count % 2 == 0 else { return nil }
        var bytes: [UInt8] = []
        bytes.reserveCapacity(hexString.count / 2)
        var high: UInt8?
        for character in hexString.utf8 {
            let nibble: UInt8
            switch character {
            case 0x30 ... 0x39: nibble = character - 0x30
            case 0x41 ... 0x46: nibble = character - 0x41 + 10
            case 0x61 ... 0x66: nibble = character - 0x61 + 10
            default: return nil
            }
            if let value = high {
                bytes.append(value << 4 | nibble)
                high = nil
            } else {
                high = nibble
            }
        }
        self = Data(bytes)
    }

    var hexString: String {
        map { String(format: "%02x", $0) }.joined()
    }
}

@Suite("Tandem big integer") struct TandemBigUIntTests {
    @Test("Parses and re-encodes hexadecimal") func hexRoundTrip() {
        let value = TandemBigUInt(hex: "0123456789abcdef0011")
        #expect(value?.bigEndianBytes.hexString == "0123456789abcdef0011")
        // Leading zeros are stripped, matching BouncyCastle's unsigned encoding.
        #expect(TandemBigUInt(hex: "0000ff")?.bigEndianBytes.hexString == "ff")
        #expect(TandemBigUInt(hex: "00")?.isZero == true)
        #expect(TandemBigUInt(hex: "zz") == nil)
    }

    @Test("Pads to a fixed width") func fixedWidth() {
        let value = TandemBigUInt(hex: "ff")!
        #expect(value.bigEndianBytes(width: 4)?.hexString == "000000ff")
        // A value that does not fit is rejected rather than truncated.
        #expect(TandemBigUInt(hex: "0102030405")!.bigEndianBytes(width: 4) == nil)
    }

    @Test("Adds, subtracts and multiplies across limb boundaries") func arithmetic() {
        let maxLimb = TandemBigUInt(UInt64.max)
        let one = TandemBigUInt(1)
        // (2^64 - 1) + 1 == 2^64
        #expect((maxLimb + one).bigEndianBytes.hexString == "010000000000000000")
        // 2^64 - 1 == (2^64) - 1
        #expect(((maxLimb + one) - one) == maxLimb)
        // (2^64 - 1)^2
        #expect((maxLimb * maxLimb).bigEndianBytes.hexString == "fffffffffffffffe0000000000000001")
        #expect((maxLimb * TandemBigUInt()).isZero)
    }

    @Test("Reduces values wider than the modulus") func modulo() {
        // Multi-limb divisor, exercising the normalization and quotient-estimate
        // correction paths.
        let modulus = TandemBigUInt(hex: "0100000000000000000000000000000000")! // 2^128
        let value = TandemBigUInt(hex: "0123456789abcdef0123456789abcdef0123456789abcdef")!
        #expect(value.modulo(modulus).bigEndianBytes.hexString == "0123456789abcdef0123456789abcdef")
        // Single-limb divisor path.
        #expect(TandemBigUInt(hex: "0123456789abcdef01")!.modulo(TandemBigUInt(255)) == TandemBigUInt(196))
        #expect(TandemBigUInt(1000).modulo(TandemBigUInt(7)) == TandemBigUInt(6))
        // Divisor larger than the dividend is returned unchanged.
        #expect(TandemBigUInt(5).modulo(TandemBigUInt(9)) == TandemBigUInt(5))
        // An exact multiple reduces to zero.
        #expect(TandemBigUInt.modMul(TandemP256.p, TandemBigUInt(3), TandemP256.p).isZero)
    }

    @Test("Inverts modulo the P-256 prime") func modularInverse() {
        let prime = TandemP256.p
        for hex in ["02", "03", "abcdef", "6b17d1f2e12c4247f8bce6e563a440f277037d812deb33a0f4a13945d898c296"] {
            let value = TandemBigUInt(hex: hex)!
            let inverse = TandemBigUInt.modInversePrime(value, prime)
            #expect(TandemBigUInt.modMul(value, inverse, prime) == TandemBigUInt(1))
        }
        #expect(TandemBigUInt.modInversePrime(TandemBigUInt(), prime).isZero)
    }
}

@Suite("Tandem P-256 curve") struct TandemP256Tests {
    @Test("The compiled-in generator is on the curve") func generatorOnCurve() {
        let affine = TandemP256.generator.affine
        #expect(affine != nil)
        #expect(TandemP256.isOnCurve(x: affine!.x, y: affine!.y))
    }

    @Test("Encodes the generator uncompressed") func generatorEncoding() {
        #expect(TandemP256.encode(TandemP256.generator)?.hexString == TandemTestVectors.generatorEncoding)
    }

    @Test("Multiplying by the group order gives the point at infinity") func orderIsCorrect() {
        #expect(TandemP256.multiply(TandemP256.generator, by: TandemP256.n).isInfinity)
    }

    @Test("Scalar multiplication is a group homomorphism") func homomorphism() {
        let a = TandemBigUInt(12345)
        let b = TandemBigUInt(67890)
        let sum = TandemBigUInt.modAdd(a, b, TandemP256.n)
        let left = TandemP256.multiply(TandemP256.generator, by: sum)
        let right = TandemP256.add(
            TandemP256.multiply(TandemP256.generator, by: a),
            TandemP256.multiply(TandemP256.generator, by: b)
        )
        #expect(left == right)
        #expect(TandemP256.double(TandemP256.generator) == TandemP256.add(TandemP256.generator, TandemP256.generator))
    }

    @Test("Round-trips a point through its encoding") func encodeDecode() throws {
        let point = TandemP256.multiply(TandemP256.generator, by: TandemBigUInt(9973))
        let encoded = try #require(TandemP256.encode(point))
        let decoded = try TandemP256.decode(encoded)
        #expect(decoded == point)
    }

    @Test("Rejects points that are not on the curve") func rejectsInvalidPoints() {
        // Valid encoding shape, but the coordinates do not satisfy the curve
        // equation — the check that blocks an invalid-curve attack.
        let bogus = Data([0x04]) + Data(repeating: 0x01, count: 64)
        #expect(throws: TandemP256.CurveError.self) { try TandemP256.decode(bogus) }
        // Wrong length and wrong prefix are rejected too.
        #expect(throws: TandemP256.CurveError.self) { try TandemP256.decode(Data([0x04, 0x01])) }
        #expect(throws: TandemP256.CurveError.self) {
            try TandemP256.decode(Data([0x02]) + Data(repeating: 0x01, count: 64))
        }
    }
}

@Suite("Tandem EC-JPAKE") struct TandemEcJpakeTests {
    @Test("Reproduces the all-ones reference exchange") func allZeroVector() throws {
        let client = TandemEcJpake(
            role: .client,
            secret: Data(TandemTestVectors.allZeroPairingCode.utf8),
            random: ScriptedRandomSource(
                scalarHex: TandemTestVectors.allZeroScalars,
                blockHex: TandemTestVectors.allZeroBlocks
            )
        )
        let round1 = try client.round1()
        #expect(round1.hexString == TandemTestVectors.allZeroClientRound1)
        try client.readRound1(Data(hexString: TandemTestVectors.allZeroServerRound1)!)
        let round2 = try client.round2()
        #expect(round2.hexString == TandemTestVectors.allZeroClientRound2)
        try client.readRound2(Data(hexString: TandemTestVectors.allZeroServerRound2)!)
        let derived = try client.deriveSecret()
        #expect(derived.hexString == TandemTestVectors.allZeroDerivedSecret)
    }

    @Test("Reproduces the reference exchange with non-trivial scalars") func counterVector() throws {
        let client = TandemEcJpake(
            role: .client,
            secret: Data(TandemTestVectors.counterPairingCode.utf8),
            random: ScriptedRandomSource(
                scalarHex: TandemTestVectors.counterClientScalars,
                blockHex: TandemTestVectors.counterClientBlocks
            )
        )
        let round1 = try client.round1()
        #expect(round1.hexString == TandemTestVectors.counterClientRound1)
        try client.readRound1(Data(hexString: TandemTestVectors.counterServerRound1)!)
        let round2 = try client.round2()
        #expect(round2.hexString == TandemTestVectors.counterClientRound2)
        try client.readRound2(Data(hexString: TandemTestVectors.counterServerRound2)!)
        let derived = try client.deriveSecret()
        #expect(derived.hexString == TandemTestVectors.counterDerivedSecret)
    }

    @Test("Two peers with the same code agree on a secret") func liveExchange() throws {
        let secret = Data("246810".utf8)
        let client = TandemEcJpake(role: .client, secret: secret)
        let server = TandemEcJpake(role: .server, secret: secret)

        let clientRound1 = try client.round1()
        let serverRound1 = try server.round1()
        #expect(clientRound1.count == 330)
        try client.readRound1(serverRound1)
        try server.readRound1(clientRound1)

        let clientRound2 = try client.round2()
        let serverRound2 = try server.round2()
        // The client sends no curve id; the server prefixes one.
        #expect(clientRound2.count == 165)
        #expect(serverRound2.count == 168)
        try client.readRound2(serverRound2)
        try server.readRound2(clientRound2)

        let clientSecret = try client.deriveSecret()
        let serverSecret = try server.deriveSecret()
        #expect(clientSecret.count == 32)
        #expect(clientSecret == serverSecret)
    }

    @Test("Peers with different codes do not agree") func mismatchedCodes() throws {
        let client = TandemEcJpake(role: .client, secret: Data("111111".utf8))
        let server = TandemEcJpake(role: .server, secret: Data("222222".utf8))

        // The zero-knowledge proofs still verify — they prove knowledge of the
        // ephemeral keys, not of the password — so the mismatch only shows up as
        // a different derived secret, which is exactly what key confirmation
        // (round 4) is there to catch.
        let clientRound1 = try client.round1()
        let serverRound1 = try server.round1()
        try client.readRound1(serverRound1)
        try server.readRound1(clientRound1)
        let clientRound2 = try client.round2()
        let serverRound2 = try server.round2()
        try client.readRound2(serverRound2)
        try server.readRound2(clientRound2)
        let clientSecret = try client.deriveSecret()
        let serverSecret = try server.deriveSecret()
        #expect(clientSecret != serverSecret)
    }

    @Test("Rejects a tampered zero-knowledge proof") func tamperedProof() throws {
        let client = TandemEcJpake(role: .client, secret: Data("135790".utf8))
        _ = try client.round1()
        var forged = Data(hexString: TandemTestVectors.allZeroServerRound1)!
        // Corrupt the last byte of the first proof's response scalar.
        forged[164] = forged[164] ^ 0xFF
        #expect(throws: TandemJpakeError.self) { try client.readRound1(forged) }
    }

    @Test("Refuses to run rounds out of order") func stateMachine() throws {
        let client = TandemEcJpake(role: .client, secret: Data("112233".utf8))
        #expect(throws: TandemJpakeError.self) { try client.round2() }
        #expect(throws: TandemJpakeError.self) { try client.deriveSecret() }
        _ = try client.round1()
        #expect(throws: TandemJpakeError.self) { try client.round2() }
    }
}

@Suite("Tandem JPAKE key derivation") struct TandemJpakeKeyTests {
    @Test("Derives the session key the pump expects") func sessionKey() throws {
        let derivedSecret = Data(hexString: TandemTestVectors.allZeroDerivedSecret)!
        let nonce = Data(hexString: "0102030405060708")!
        let key = TandemJpakeKeys.sessionKey(derivedSecret: derivedSecret, pumpNonce: nonce)
        #expect(key.hexString == "f129f51702fec6d2d49d9ff262c6fbe77bbf6e97a9dd1b69ae344cb1c5b425ea")
    }

    @Test("Computes the key-confirmation digest") func confirmationDigest() throws {
        let derivedSecret = Data(hexString: TandemTestVectors.allZeroDerivedSecret)!
        let key = TandemJpakeKeys.sessionKey(
            derivedSecret: derivedSecret,
            pumpNonce: Data(hexString: "0102030405060708")!
        )
        let digest = TandemJpakeKeys.confirmationDigest(
            nonce: Data(hexString: "aabbccddeeff0011")!,
            sessionKey: key
        )
        #expect(digest.hexString == "ca4781f1a439001570db797f39655b04d3b08f44a6019740c398c1114cebc751")
    }

    @Test("Accepts only well-formed 6-digit pairing codes") func pairingCodeParsing() {
        #expect(TandemPumpSession.jpakePairingCodeBytes("123456") == Data("123456".utf8))
        // Separators and whitespace are stripped, as the pump prints the code in
        // groups.
        #expect(TandemPumpSession.jpakePairingCodeBytes("12-34 56") == Data("123456".utf8))
        #expect(TandemPumpSession.jpakePairingCodeBytes("12345") == nil)
        #expect(TandemPumpSession.jpakePairingCodeBytes("1234567") == nil)
        #expect(TandemPumpSession.jpakePairingCodeBytes("12345a") == nil)
        #expect(TandemPumpSession.isJpakePairingCode("000000"))
        #expect(!TandemPumpSession.isJpakePairingCode("ABCDEFGH12345678"))
    }
}
