import CryptoKit
import Foundation

/// Web Push (RFC 8030/8188/8291/8292) delivery for web viewers — browser
/// followers that watch glucose, insulin and carb data from a web page.
///
/// The browser's push subscription carries its own P-256 key pair and auth
/// secret, generated by the browser; the push service relays only ciphertext
/// it cannot read. On top of that transport encryption the payload itself is
/// the same AES-256-GCM blob every other follower transport carries, keyed by
/// the follower's pairing secret — so a leaked subscription lets nobody forge
/// a status the viewer would accept.
///
/// The host authenticates to the push service with a VAPID key pair it
/// generates locally (`FollowerPairingManager.vapidPrivateKey`). No account
/// with any push provider is involved: the key is self-chosen, and the
/// subscription is bound to it when the browser subscribes.
enum WebPushError: LocalizedError {
    case invalidSubscription
    case invalidVAPIDKey
    case payloadTooLarge
    /// The push service says this subscription no longer exists (HTTP
    /// 404/410). The viewer must re-register from its browser.
    case subscriptionGone
    case transportFailure(String)

    var errorDescription: String? {
        switch self {
        case .invalidSubscription:
            return "The web viewer's push subscription is malformed."
        case .invalidVAPIDKey:
            return "The stored VAPID key is invalid."
        case .payloadTooLarge:
            return "The web push payload exceeds the 4 KB limit."
        case .subscriptionGone:
            return "The web viewer's push subscription has expired."
        case let .transportFailure(reason):
            return "Web push failed: \(reason)"
        }
    }
}

/// RFC 8291 message encryption (the `aes128gcm` content coding of RFC 8188,
/// keyed by ECDH against the subscription's keys).
enum WebPushEncryptor {
    /// The most plaintext that fits a push-service message: services cap the
    /// whole body at 4096 bytes, of which the content-coding header takes
    /// 16 (salt) + 4 (rs) + 1 (idlen) + 65 (sender public key) = 86 and the
    /// single record another 1 (padding delimiter) + 16 (GCM tag).
    static let maximumPlaintextBytes = 4096 - 86 - 17

    /// Encrypts `plaintext` for a subscription, returning the complete
    /// `aes128gcm` body (header || ciphertext || tag).
    ///
    /// `ephemeralKey` and `salt` are injectable so the RFC 8291 Appendix A
    /// vector can be pinned in tests; production callers take the random
    /// defaults.
    static func encrypt(
        plaintext: Data,
        receiverPublicKey: Data,
        authSecret: Data,
        ephemeralKey: P256.KeyAgreement.PrivateKey = P256.KeyAgreement.PrivateKey(),
        salt: Data? = nil
    ) throws -> Data {
        guard plaintext.count <= maximumPlaintextBytes else { throw WebPushError.payloadTooLarge }
        guard receiverPublicKey.count == 65, authSecret.count == 16 else {
            throw WebPushError.invalidSubscription
        }
        guard let uaPublic = try? P256.KeyAgreement.PublicKey(x963Representation: receiverPublicKey) else {
            throw WebPushError.invalidSubscription
        }

        let saltBytes: Data
        if let salt {
            guard salt.count == 16 else { throw WebPushError.invalidSubscription }
            saltBytes = salt
        } else {
            var random = [UInt8](repeating: 0, count: 16)
            let status = SecRandomCopyBytes(kSecRandomDefault, random.count, &random)
            guard status == errSecSuccess else {
                throw WebPushError.transportFailure("Failed to generate a random salt")
            }
            saltBytes = Data(random)
        }

        let asPublic = ephemeralKey.publicKey.x963Representation
        let sharedSecret = try ephemeralKey.sharedSecretFromKeyAgreement(with: uaPublic)

        // RFC 8291 §3.3–3.4: IKM = HKDF(salt: auth_secret, ikm: ECDH secret,
        // info: "WebPush: info" || 0x00 || ua_public || as_public).
        var keyInfo = Data("WebPush: info".utf8)
        keyInfo.append(0)
        keyInfo.append(receiverPublicKey)
        keyInfo.append(asPublic)
        let ikm = sharedSecret.hkdfDerivedSymmetricKey(
            using: SHA256.self,
            salt: authSecret,
            sharedInfo: keyInfo,
            outputByteCount: 32
        )

        // RFC 8188 §2.2–2.3: content-encryption key and nonce from the salt.
        let cek = HKDF<SHA256>.deriveKey(
            inputKeyMaterial: ikm,
            salt: saltBytes,
            info: Data("Content-Encoding: aes128gcm".utf8) + [0],
            outputByteCount: 16
        )
        let nonceKey = HKDF<SHA256>.deriveKey(
            inputKeyMaterial: ikm,
            salt: saltBytes,
            info: Data("Content-Encoding: nonce".utf8) + [0],
            outputByteCount: 12
        )
        let nonce = try AES.GCM.Nonce(data: nonceKey.withUnsafeBytes { Data($0) })

        // Single record: plaintext, the 0x02 delimiter of a last record, tag.
        var record = plaintext
        record.append(2)
        let sealed = try AES.GCM.seal(record, using: cek, nonce: nonce)

        var body = saltBytes
        var recordSize = UInt32(4096).bigEndian
        body.append(Data(bytes: &recordSize, count: 4))
        body.append(UInt8(asPublic.count))
        body.append(asPublic)
        body.append(sealed.ciphertext)
        body.append(sealed.tag)
        return body
    }
}

/// RFC 8292 VAPID: a self-signed ES256 JWT proving to the push service which
/// application server is speaking, bound to the key the browser subscribed
/// with.
enum WebPushVAPID {
    /// Who to contact about this application server. VAPID wants a URL or
    /// mailto:; the project page is the honest answer for a self-built app.
    static let subject = "https://github.com/nightscout/Trio"

    /// JWTs are valid for at most 24 hours; 12 leaves room to cache.
    static let tokenLifetime: TimeInterval = 12 * 60 * 60

    /// The push-service origin the JWT is addressed to.
    static func audience(forEndpoint endpoint: URL) throws -> String {
        guard let scheme = endpoint.scheme, let host = endpoint.host else {
            throw WebPushError.invalidSubscription
        }
        if let port = endpoint.port, port != 443 {
            return "\(scheme)://\(host):\(port)"
        }
        return "\(scheme)://\(host)"
    }

    static func base64URL(_ data: Data) -> String {
        data.base64EncodedString()
            .replacingOccurrences(of: "+", with: "-")
            .replacingOccurrences(of: "/", with: "_")
            .replacingOccurrences(of: "=", with: "")
    }

    /// Builds the `Authorization: vapid t=<jwt>, k=<public key>` header value.
    static func authorizationHeader(
        endpoint: URL,
        privateKeyRaw: Data,
        now: Date = Date()
    ) throws -> String {
        guard let key = try? P256.Signing.PrivateKey(rawRepresentation: privateKeyRaw) else {
            throw WebPushError.invalidVAPIDKey
        }

        let headerJSON = Data(#"{"alg":"ES256","typ":"JWT"}"#.utf8)
        let claims: [String: Any] = [
            "aud": try audience(forEndpoint: endpoint),
            "exp": Int(now.timeIntervalSince1970 + tokenLifetime),
            "sub": subject
        ]
        let claimsJSON = try JSONSerialization.data(withJSONObject: claims, options: [.sortedKeys])
        let signingInput = "\(base64URL(headerJSON)).\(base64URL(claimsJSON))"
        // CryptoKit's rawRepresentation is the 64-byte r || s form JOSE wants.
        let signature = try key.signature(for: Data(signingInput.utf8)).rawRepresentation
        let jwt = "\(signingInput).\(base64URL(signature))"
        let publicKey = base64URL(key.publicKey.x963Representation)
        return "vapid t=\(jwt), k=\(publicKey)"
    }
}

/// Sends encrypted payloads to a web viewer's push subscription.
final class WebPushMessenger {
    static let shared = WebPushMessenger()

    private init() {}

    private struct CachedHeader {
        let value: String
        let expiry: Date
    }

    /// VAPID JWTs are per push-service origin; cache them the way APNS JWTs
    /// are cached rather than signing one per push.
    private var headerCache: [String: CachedHeader] = [:]
    private let cacheQueue = DispatchQueue(label: "WebPushMessenger.cache")

    /// Delivers one JSON payload to a viewer's subscription.
    ///
    /// - Parameters:
    ///   - urgency: RFC 8030 urgency — "normal" for status, "high" for alerts.
    ///   - topic: when set, the push service keeps only the newest queued
    ///     message with the same topic for an offline browser; status pushes
    ///     use this so a browser that was closed overnight wakes to one
    ///     snapshot, not hundreds.
    ///   - ttl: seconds the push service may hold an undeliverable message.
    func send(
        payload: [String: Any],
        to follower: PairedFollower,
        urgency: String,
        topic: String?,
        ttl: Int
    ) async throws {
        guard let endpointString = follower.pushToken,
              let endpoint = URL(string: endpointString),
              endpoint.scheme == "https",
              let p256dh = Self.base64URLDecode(follower.webPushP256dh ?? ""),
              let auth = Self.base64URLDecode(follower.webPushAuth ?? "")
        else {
            throw WebPushError.invalidSubscription
        }

        let vapidKeyBase64 = FollowerPairingManager.shared.vapidPrivateKey
        guard let vapidKey = Data(base64Encoded: vapidKeyBase64), !vapidKey.isEmpty else {
            throw WebPushError.invalidVAPIDKey
        }

        let plaintext = try JSONSerialization.data(withJSONObject: payload, options: [.sortedKeys])
        let body = try WebPushEncryptor.encrypt(
            plaintext: plaintext,
            receiverPublicKey: p256dh,
            authSecret: auth
        )

        var request = URLRequest(url: endpoint)
        request.httpMethod = "POST"
        request.setValue(try authorization(for: endpoint, privateKeyRaw: vapidKey), forHTTPHeaderField: "Authorization")
        request.setValue("aes128gcm", forHTTPHeaderField: "Content-Encoding")
        request.setValue("application/octet-stream", forHTTPHeaderField: "Content-Type")
        request.setValue(String(ttl), forHTTPHeaderField: "TTL")
        request.setValue(urgency, forHTTPHeaderField: "Urgency")
        if let topic {
            request.setValue(topic, forHTTPHeaderField: "Topic")
        }
        request.httpBody = body

        let (data, response) = try await URLSession.shared.data(for: request)
        guard let httpResponse = response as? HTTPURLResponse else {
            throw WebPushError.transportFailure("No HTTP response from the push service")
        }
        switch httpResponse.statusCode {
        case 200 ... 299:
            return
        case 404, 410:
            throw WebPushError.subscriptionGone
        default:
            let detail = String(data: data, encoding: .utf8) ?? ""
            throw WebPushError.transportFailure("HTTP \(httpResponse.statusCode): \(detail.prefix(200))")
        }
    }

    private func authorization(for endpoint: URL, privateKeyRaw: Data) throws -> String {
        let origin = try WebPushVAPID.audience(forEndpoint: endpoint)
        if let cached = cacheQueue.sync(execute: { headerCache[origin] }), cached.expiry > Date() {
            return cached.value
        }
        let header = try WebPushVAPID.authorizationHeader(endpoint: endpoint, privateKeyRaw: privateKeyRaw)
        // Refresh an hour before the JWT inside expires.
        let expiry = Date().addingTimeInterval(WebPushVAPID.tokenLifetime - 3600)
        cacheQueue.sync { headerCache[origin] = CachedHeader(value: header, expiry: expiry) }
        return header
    }

    /// The keys inside a browser's `PushSubscription.toJSON()` are unpadded
    /// base64url.
    static func base64URLDecode(_ string: String) -> Data? {
        guard !string.isEmpty else { return nil }
        var base64 = string
            .replacingOccurrences(of: "-", with: "+")
            .replacingOccurrences(of: "_", with: "/")
        while base64.count % 4 != 0 {
            base64.append("=")
        }
        return Data(base64Encoded: base64)
    }
}
